CREATE TABLE IF NOT EXISTS USERS (
    USER_ID             BIGINT          AUTO_INCREMENT PRIMARY KEY,
    EMAIL               VARCHAR(100)    NOT NULL UNIQUE,
    PASSWORD            VARCHAR(255),
    NAME                VARCHAR(50),
    NICKNAME            VARCHAR(50)     UNIQUE,
    PHONE               VARCHAR(20),
    ADDRESS             VARCHAR(255),
    ADDRESS_DETAIL      VARCHAR(255),
    RESIDENT_NO         VARCHAR(255),
    EMAIL_VERIFIED      CHAR(1)         DEFAULT 'N',
    EMAIL_VERIFY_TOKEN  VARCHAR(255),
    LOGIN_FAIL_CNT      INT             DEFAULT 0,
    ACCOUNT_LOCKED      CHAR(1)         DEFAULT 'N',
    CREATED_AT          DATETIME        DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS STOCK_ITEM (
    ITEM_ID     BIGINT          AUTO_INCREMENT PRIMARY KEY,
    TICKER      VARCHAR(20)     NOT NULL UNIQUE,
    ITEM_NM     VARCHAR(100)    NOT NULL,
    MARKET      VARCHAR(20),
    CREATED_AT  DATETIME        DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS STOCK_PRICE (
    PRICE_ID    BIGINT          AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID     BIGINT          NOT NULL,
    OPEN_PRICE  BIGINT,
    CLOSE_PRICE BIGINT,
    HIGH_PRICE  BIGINT,
    LOW_PRICE   BIGINT,
    VOLUME      BIGINT,
    TRADE_DATE  DATE,
    FOREIGN KEY (ITEM_ID) REFERENCES STOCK_ITEM(ITEM_ID)
);

CREATE TABLE IF NOT EXISTS USER_WATCHLIST (
    WATCH_ID    BIGINT      AUTO_INCREMENT PRIMARY KEY,
    USER_ID     BIGINT      NOT NULL,
    ITEM_ID     BIGINT      NOT NULL,
    ADDED_AT    DATETIME    DEFAULT NOW(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES STOCK_ITEM(ITEM_ID)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO (
    PORTFOLIO_ID    BIGINT          AUTO_INCREMENT PRIMARY KEY,
    USER_ID         BIGINT          NOT NULL,
    TICKER          VARCHAR(20)     NOT NULL,
    STOCK_NAME      VARCHAR(100)    NOT NULL,
    QUANTITY        DECIMAL(12,2)   NOT NULL,
    BUY_PRICE       BIGINT          NOT NULL,
    BUY_DATE        VARCHAR(8)      NOT NULL,
    CREATED_AT      DATETIME        DEFAULT NOW(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS PRICE_ALERT (
    ALERT_ID        BIGINT          AUTO_INCREMENT PRIMARY KEY,
    USER_ID         BIGINT          NOT NULL,
    ITEM_ID         BIGINT,
    TICKER          VARCHAR(20)     NOT NULL,
    STOCK_NAME      VARCHAR(100),
    TARGET_PRICE    BIGINT          NOT NULL,
    ALERT_TYPE      VARCHAR(10)     NOT NULL,
    IS_TRIGGERED    CHAR(1)         DEFAULT 'N',
    CREATED_AT      DATETIME        DEFAULT NOW(),
    TRIGGERED_AT    DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKEN (
    TOKEN_ID    BIGINT          AUTO_INCREMENT PRIMARY KEY,
    USER_ID     BIGINT          NOT NULL,
    TOKEN       VARCHAR(512)    NOT NULL,
    EXPIRED_AT  DATETIME        NOT NULL,
    CREATED_AT  DATETIME        DEFAULT NOW(),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGE (
    MSG_ID      BIGINT          AUTO_INCREMENT PRIMARY KEY,
    TICKER      VARCHAR(20)     NOT NULL,
    USER_EMAIL  VARCHAR(100),
    NICKNAME    VARCHAR(50),
    CONTENT     TEXT,
    CREATED_AT  DATETIME        DEFAULT NOW()
);