CREATE TABLE IF NOT EXISTS USERS (
    USER_ID               INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL                 VARCHAR(120) NOT NULL,
    PASSWORD              VARCHAR(255) NOT NULL,
    NAME                  VARCHAR(50),
    NICKNAME              VARCHAR(50),
    PHONE                 VARCHAR(20),
    ADDRESS               VARCHAR(255),
    ADDRESS_DETAIL        VARCHAR(255),
    RESIDENT_NO           VARCHAR(255),
    ROLE                  VARCHAR(20)  DEFAULT 'USER',
    EMAIL_VERIFIED        CHAR(1)      DEFAULT 'N',
    EMAIL_VERIFY_TOKEN    VARCHAR(100),
    LOGIN_FAIL_CNT        INT          DEFAULT 0,
    ACCOUNT_LOCKED        CHAR(1)      DEFAULT 'N',
    PASSWORD_RESET_TOKEN  VARCHAR(100),
    PASSWORD_RESET_EXPIRY DATETIME,
    PROFILE_IMAGE_URL     VARCHAR(500),
    CREATED_AT            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT            DATETIME,
    DELETE_REASON         VARCHAR(500),
    FORCE_PW_CHANGE       CHAR(1)      DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS USER_SOCIAL (
    SOCIAL_ID      INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID        INT NOT NULL,
    PROVIDER       VARCHAR(20) NOT NULL,
    PROVIDER_EMAIL VARCHAR(120),
    CREATED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKEN (
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    INT NOT NULL,
    TOKEN      VARCHAR(500) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STOCK_ITEM (
    ITEM_ID    INT AUTO_INCREMENT PRIMARY KEY,
    TICKER     VARCHAR(20) NOT NULL UNIQUE,
    ITEM_NM    VARCHAR(120),
    MARKET     VARCHAR(20),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_WATCHLIST (
    WATCHLIST_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      INT NOT NULL,
    ITEM_ID      INT NOT NULL,
    ADDED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP
);
